# Generated by Django 5.1.4 on 2025-01-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
