# Generated by Django 5.1.4 on 2025-01-10 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Full name contains invalid characters. Please use only letters, spaces, hyphen, and apostrophe.', regex="^[a-zA-Z\\s\\-\\' ]{2,50}$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_profile',
            field=models.JSONField(blank=True, default={}, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
