# Generated by Django 5.1.4 on 2025-01-10 23:06

import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_user_health_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='health_profile',
            field=models.JSONField(blank=True, null=True, validators=[user_auth.models.validate_health_profile]),
        ),
    ]
