# Generated by Django 5.1.4 on 2025-02-08 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.diagnosis')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.disease')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diseases',
            field=models.ManyToManyField(blank=True, through='symptom_checker.DiagnosisDisease', to='symptom_checker.disease'),
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(blank=True, through='symptom_checker.DiseaseSymptom', to='symptom_checker.symptom'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='symptom_checker.symptom'),
        ),
    ]
