# Generated by Django 5.2.1 on 2025-05-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('common_symptoms', models.TextField(blank=True, help_text='Comma-separated list of common symptoms')),
                ('prevalence', models.CharField(blank=True, choices=[('very_common', 'Very Common'), ('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare')], max_length=100)),
                ('risk_factors', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-threatening')], max_length=100)),
                ('typical_duration', models.CharField(blank=True, max_length=100)),
                ('contagious', models.BooleanField(null=True)),
                ('icd11_code', models.CharField(blank=True, max_length=20)),
                ('synonyms', models.TextField(blank=True, help_text='Comma-separated list of alternative names')),
            ],
        ),
        migrations.CreateModel(
            name='DO_Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('is_a', 'Is a'), ('part_of', 'Part of'), ('related_to', 'Related to'), ('subclass_of', 'Subclass of')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DO_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
                ('is_obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('diagnosed', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSymptomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_noticed', models.DateField()),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomDOTermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.8)),
            ],
        ),
    ]
