# Generated by Django 5.2.1 on 2025-05-25 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptom_checker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisdisease',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.diagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosissymptom',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.diagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosisdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.disease'),
        ),
        migrations.AddField(
            model_name='do_relationship',
            name='do_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='symptom_checker.do_term'),
        ),
        migrations.AddField(
            model_name='do_relationship',
            name='related_do_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='symptom_checker.do_term'),
        ),
        migrations.AddField(
            model_name='disease',
            name='do_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptom_checker.do_term'),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientsymptomhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientsymptomhistory',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.symptom'),
        ),
        migrations.AddField(
            model_name='diagnosissymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.symptom'),
        ),
        migrations.AddField(
            model_name='symptomdotermmapping',
            name='do_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.do_term'),
        ),
        migrations.AddField(
            model_name='symptomdotermmapping',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='do_relationship',
            unique_together={('do_term', 'relationship_type', 'related_do_term')},
        ),
        migrations.AlterUniqueTogether(
            name='symptomdotermmapping',
            unique_together={('symptom', 'do_term')},
        ),
    ]
