# Generated by Django 5.1.4 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DO_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DO_Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=255)),
                ('do_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.do_term')),
                ('related_do_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_do_term', to='symptom_checker.do_term')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='do_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptom_checker.do_term'),
        ),
    ]
