# Generated by Django 5.2 on 2025-04-27 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_do_term_do_relationship_disease_do_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='do_term',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='do_relationship',
            name='do_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='symptom_checker.do_term'),
        ),
        migrations.AlterField(
            model_name='do_relationship',
            name='related_do_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='symptom_checker.do_term'),
        ),
        migrations.AlterField(
            model_name='do_relationship',
            name='relationship_type',
            field=models.CharField(choices=[('is_a', 'Is a'), ('part_of', 'Part of'), ('related_to', 'Related to'), ('subclass_of', 'Subclass of')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='do_relationship',
            unique_together={('do_term', 'relationship_type', 'related_do_term')},
        ),
        migrations.CreateModel(
            name='DiagnosisSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(default=1)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.diagnosis')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomDOTermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.8)),
                ('do_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.do_term')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_checker.symptom')),
            ],
            options={
                'unique_together': {('symptom', 'do_term')},
            },
        ),
        migrations.DeleteModel(
            name='DiseaseSymptom',
        ),
    ]
