# Generated by Django 5.1.4 on 2025-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
