# Generated by Django 5.2 on 2025-04-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_recommender', '0005_remove_article_categories_remove_article_embeddings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_headers/'),
        ),
    ]
